// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD77e0Gtl-ye6H0QQvv20o31RHN-O2R9DE',
    appId: '1:326918587685:web:0773bed77481d51a6e46cc',
    messagingSenderId: '326918587685',
    projectId: 'leema-inventory-app',
    authDomain: 'leema-inventory-app.firebaseapp.com',
    storageBucket: 'leema-inventory-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPcSPcQ-xDKjlpzhGza3T-iq7DTliFrqo',
    appId: '1:326918587685:android:34c3c7d574d73d926e46cc',
    messagingSenderId: '326918587685',
    projectId: 'leema-inventory-app',
    storageBucket: 'leema-inventory-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkJ-NOB7oVC9OliHFOXg53TeyFQrtsjUA',
    appId: '1:326918587685:ios:c81326385ba746b06e46cc',
    messagingSenderId: '326918587685',
    projectId: 'leema-inventory-app',
    storageBucket: 'leema-inventory-app.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkJ-NOB7oVC9OliHFOXg53TeyFQrtsjUA',
    appId: '1:326918587685:ios:c81326385ba746b06e46cc',
    messagingSenderId: '326918587685',
    projectId: 'leema-inventory-app',
    storageBucket: 'leema-inventory-app.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD77e0Gtl-ye6H0QQvv20o31RHN-O2R9DE',
    appId: '1:326918587685:web:76a004e171f16fb46e46cc',
    messagingSenderId: '326918587685',
    projectId: 'leema-inventory-app',
    authDomain: 'leema-inventory-app.firebaseapp.com',
    storageBucket: 'leema-inventory-app.firebasestorage.app',
  );
}
